BREW := $(shell command -v brew 2> /dev/null)
CCLS_VERSION := 7445891
CCLS_REPO_DIR := ~/.ccls/repo
CCLS_BUILD_DIR := ~/.ccls/build
CCLS_INSTALL_PREFIX := ~/.local
FZF_DIR := $HOME/.fzf
MAKEFILE_PATH := $(abspath $(lastword ${MAKEFILE_LIST}))
MAKEFILE_DIR := $(dir ${MAKEFILE_PATH})
#---------------------------------------------------------------------------
install-brew:
ifndef BREW
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	@echo "Found Homebrew: ${BREW}"
endif
#---------------------------------------------------------------------------
install-zsh:
	brew install zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
	# disable plugins from main .zshrc to load custom plugin settings
	sed -i.bak 's/^plugins=.*/source ~\/.oh-my-zsh\/custom\/plugins.zsh/' ~/.zshrc
#---------------------------------------------------------------------------
install-fzf:
	brew install fd
	brew install fzf
	echo "run the key binding install command!"
#---------------------------------------------------------------------------
install-ccls:
	rm -rf $(CCLS_REPO_DIR) $(CCLS_BUILD_DIR)
	git clone --recursive https://github.com/MaskRay/ccls $(CCLS_REPO_DIR)
	cd $(CCLS_REPO_DIR) && git checkout $(CCLS_VERSION)
	cd $(CCLS_REPO_DIR) && git submodule update --init --recursive
	mkdir -p $(CCLS_BUILD_DIR) $(CCLS_INSTALL_PREFIX)
	cd $(CCLS_BUILD_DIR) && cmake \
		-GNinja \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=$(CCLS_INSTALL_PREFIX) \
		-DCMAKE_PREFIX_PATH=$(LLVM_PREFIX_PATH) \
		$(CCLS_REPO_DIR)
	cd $(CCLS_BUILD_DIR) && ninja
	cd $(CCLS_BUILD_DIR) && ninja install
#---------------------------------------------------------------------------
install-neovim:
	brew install neovim
	pip3 install --user --upgrade pynvim
#---------------------------------------------------------------------------
install-monokai:
	mkdir -p ${HOME}/.vim/colors
	cd ${HOME}/.vim/colors && curl -O https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
	mkdir -p ${HOME}/.config/nvim/colors
	cd ${HOME}/.config/nvim/colors && curl -O https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
#---------------------------------------------------------------------------
install-vim-plug:
	# Vim
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	# NeoVim
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#---------------------------------------------------------------------------
create-directories:
	@mkdir -p ~/.config
	@mkdir -p ~/.config/nvim
#---------------------------------------------------------------------------
install-config: create-directories
	@ln -sf ${MAKEFILE_DIR}/git.conf ${HOME}/.gitconfig
	@ln -sf ${MAKEFILE_DIR}/gdb.conf ${HOME}/.gdbinit
	@ln -sf ${MAKEFILE_DIR}/ssh.conf ${HOME}/.ssh/config
	@ln -sf ${MAKEFILE_DIR}/vim.conf ${HOME}/.config/nvim/init.vim
	@ln -sf ${MAKEFILE_DIR}/coc-settings.json ${HOME}/.config/nvim/coc-settings.json
	@ln -sf ${MAKEFILE_DIR}/custom.zsh ${HOME}/.oh-my-zsh/custom/custom.zsh
	@ln -sf ${MAKEFILE_DIR}/plugins.zsh ${HOME}/.oh-my-zsh/custom/plugins.zsh
#---------------------------------------------------------------------------
