Host naskemper
User boettcher
HostName naskemper3.informatik.tu-muenchen.de

Host webkemper
User boettcher
HostName webkemper1.informatik.tu-muenchen.de

Host scyper12
User boettcher
HostName scyper12.informatik.tu-muenchen.de

Host scyper13
User boettcher
HostName scyper13.informatik.tu-muenchen.de

Host scyper15
User boettcher
HostName scyper15.informatik.tu-muenchen.de

Host scyper1
User boettcher
HostName scyper1.informatik.tu-muenchen.de


Host skylakex
   User boettcher
   HostName atkemper4.informatik.tu-muenchen.de
   ForwardAgent yes


Host work
User boettcher
HostName deskkemper19.informatik.tu-muenchen.de
ForwardAgent yes

Host jboettcher-lx
User jbottcher
HostName 10.54.0.39
ForwardAgent yes

Host hyper2
User boettcher
HostName hyper2.informatik.tu-muenchen.de

# /home/sites/site100005947/web
Host praxis
   User ssh300010355
   HostName ganzheitliche-medizin-germering.de
   #   RemoteCommand cd /home/sites/site100005947/web && zsh -l


Host pmem1
User boettcher
HostName pmem1.db.in.tum.de
ForwardAgent yes

Host epyc1
  User boettcher
  HostName epyc1.db.in.tum.de
  ForwardAgent yes
  ForwardX11 yes

Host armmac1
  User janbo
  HostName armmac1.db.in.tum.de
  ForwardAgent yes
  ForwardX11 yes

Host lrzcluster
  User ga65saj2
  HostName testbed.cos.lrz.de
  ForwardAgent yes

Host personal-github
  HostName github.com
  IdentityFile ~/.ssh/personal_github
  IdentitiesOnly yes

Host aws-linux
   HostName ip-10-106-30-204.us-west-2.compute.internal
   User ubuntu
   IdentityFile ~/.ssh/hyper-team-extended.pem
   ForwardAgent yes

Host jboettcher-ltw
   HostName jboettcher-ltw1
   User jboettcher
   IdentityFile ~/.ssh/id_rsa
   ForwardAgent yes

Host basti-aws
   HostName ip-10-106-30-179.us-west-2.compute.internal
   User ubuntu
   IdentityFile ~/.ssh/id_rsa
   ForwardAgent yes
   SendEnv GIT_EDITOR nvim
